### ISSUE TITLE
Client Error: file_get_contents(https://api.rajaongkir.com/starter/cost): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request

### ISSUE THREAD

**Issue by Teddir** [fikrisuheri/laravel-toko-online#13]

**Comment by temmy555** [comment]
same issues, and i check it raja ongkir controller is gone

**Comment by hgreito** [comment]
bikin akun RajaOngkir dulu gan di web resminya, abis tu di user account kan ada API Code tuh, nah API codenya dimasukin ke config/rajaongkir.php

**Comment by labibs** [comment]
kalo belum muncul config/rajaongkir.php itu kenapa ya mas ?

**Comment by fikrisuheri** [comment]
Silahkan pakai yang terbaru karena repositories yang ini sudah tidak saya update

https://github.com/fikrisuheri/laravel-toko-online-anime-store

**Comment by fikrisuheri** [comment]
Silahkan pakai yang terbaru karena repositories yang ini sudah tidak saya update

https://github.com/fikrisuheri/laravel-toko-online-anime-store
